name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login Docker
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PW }}
    - name: Build the Docker image (latest-stable)
      run: docker build . --file Dockerfile --tag theesivaja/node-red-docker:latest-stable
    - name: Push the Docker image
      run: docker push theesivaja/node-red-docker:latest-stable
